Student name: Sreenidhi reddy kalakonda

700# : 700771953

ICP2

In [ ]:
#1. Create a class Employee and then do the following
#  Creating  a class Employee
class Employee:
    # Data member to count the number of Employees (a)
    employee_count = 0  # Class variable to track the total number of employees
    total_salary = 0  # Class variable to store the cumulative salary of all employees

    # then using Constructor to initialize name, family, salary, and department (b)
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        # Increment the employee count each time an instance is created
        Employee.employee_count += 1
        # Add the salary to the total salary of all employees
        Employee.total_salary += salary

    # This Function to calculate and return the average salary (c)
    @classmethod
    def average_salary(cls):
        # Calculate the average only if there are employees
        if cls.employee_count > 0:
            return cls.total_salary / cls.employee_count
        return 0  # Return 0 if no employees exist

#  Creating a Fulltime Employee class that inherits from Employee(d)
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        # we call the parent class constructor to initialize properties
        super().__init__(name, family, salary, department)

# Creating  instances of Employee and FulltimeEmployee classes and call their member functions(e)
# Creating Employee instances
employee1 = Employee("shayla", "smith", 58000, "Software development")
employee2 = Employee("kamal", "Anderson", 72000, "Marketing Analytics")
employee2 = Employee("dave", "Johnson", 90000, "Human Resources")

# Creating FulltimeEmployee instance
fulltime_employee1 = FulltimeEmployee("michael", "jackson", 70000, "Data analyst")

# Print the total number of employees (from a)
print(f"Total number of employees: {Employee.employee_count}")

# Calculate and print the average salary (from c)
print(f"Average salary of all employees: {Employee.average_salary()}")

# Print details of the FulltimeEmployee instance (inherits properties from Employee)
print(f"Fulltime Employee Details: Name - {fulltime_employee1.name}, "
      f"Department - {fulltime_employee1.department}, Salary - {fulltime_employee1.salary}")


Total number of employees: 4
Average salary of all employees: 72500.0
Fulltime Employee Details: Name - michael, Department - Data analyst, Salary - 70000


In [ ]:
import numpy as np

In [ ]:
#2. Numpy
# first we are Creating a random vector of size 20 with float values in the range 1-20
random_vector = np.random.uniform(1, 20, 20)
print("Original random vector (size 20):")
print(random_vector)

# then  Reshaping the vector to a 4x5 matrix
reshaped_matrix = random_vector.reshape(4, 5)
print("\nReshaped matrix (4x5):")
print(reshaped_matrix)

# after that  Replace the maximum value in each row with 0 (axis=1), without using a for loop
# Use broadcasting to find the max in each row and replace it with 0
max_in_rows = np.max(reshaped_matrix, axis=1, keepdims=True)  # this Finds the max in each row
reshaped_matrix[reshaped_matrix == max_in_rows] = 0           # and then replaces the  max values with 0
print("\nMatrix after replacing max in each row with 0:")
print(reshaped_matrix)


Original random vector (size 20):
[ 8.11045485  3.72284496  4.56720894  4.49776425 14.92995584  4.91431226
  6.0311795  14.9282281   8.17156387 14.47695486  7.99720304  8.93456093
 18.11319476 17.50784424 17.5817939  14.21160354  7.05669077 18.41492527
 16.2984432  14.9174407 ]

Reshaped matrix (4x5):
[[ 8.11045485  3.72284496  4.56720894  4.49776425 14.92995584]
 [ 4.91431226  6.0311795  14.9282281   8.17156387 14.47695486]
 [ 7.99720304  8.93456093 18.11319476 17.50784424 17.5817939 ]
 [14.21160354  7.05669077 18.41492527 16.2984432  14.9174407 ]]

Matrix after replacing max in each row with 0:
[[ 8.11045485  3.72284496  4.56720894  4.49776425  0.        ]
 [ 4.91431226  6.0311795   0.          8.17156387 14.47695486]
 [ 7.99720304  8.93456093  0.         17.50784424 17.5817939 ]
 [14.21160354  7.05669077  0.         16.2984432  14.9174407 ]]


VEDIO LINK:
https://1drv.ms/v/c/932e708434d17605/ESj2HgZTim9PnfxXdBCJ3EQBxvuNJ-uWyjcUpcF_ftv2Ag?e=s9h4hq